name: Tests
on:
  push:
    branches:
      - main
    paths:
      - "scripts/**/*"
      - ".github/workflows/tests.yaml"
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CI: true
jobs:
  Test:
    if: github.repository == 'evilmartians/harmony' # prevents this action from running on forks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: "deno install"

      - name: Lint
        run: "deno lint"

      - name: Type-check
        run: "deno check **/*.ts"

      - name: Build
        run: "deno task build"

      - name: Publint
        run: "deno task publint"

      - name: Run unit tests
        run: "deno task ci:test"

      - name: Generate code coverage report
        run: "deno task ci:coverage"

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@v1
        with:
          fail_ci_if_error: true
          files: ./coverage/junit.xml
          flags: unittests, ${{ runner.os }}
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./coverage/coverage.lcov
          flags: unittests, ${{ runner.os }}
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
